###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/qwasd

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name":"plate",
    "description":"best plate in town",
    "price":50,
    "url":"Url for plate",
    "discount":2
}

###
PATCH  http://localhost:3000/products/qwasd
Content-Type: application/json

{
    "name":"updated tv",
    "description":"best updated tv in town",
    "price":43,
    "url":"Url for best upated tv",
    "discount":234
}
###
DELETE http://localhost:3000/products/qwasd
Content-Type: application/json